### ISSUE TITLE
Issue - No issues!

### ISSUE THREAD

**Issue by oradomskyi** [Alice-Bob-SW/qiskit-alice-bob-provider#26]
Hi folks! 🚀

I find your Cat Qubits 🐾 an exciting technology and will be glad to develop the codebase 🙂

Do you have anything that an open-source community could contribute to? 🙄

**Comment by MaxleDrut** [comment]
Hello Oleksandr,

Sorry for the late reply, I did not see your message until yet!

We're so happy to hear you are interested by Alice & Bob's technology and code base!

At the moment, we are not set on expanding the reach of our emulators, and we are most of all looking for users that are eager to give feedback. I thereby invite you to play with the local emulator and have a look at the emulation examples we built here: https://github.com/Alice-Bob-SW/emulation-examples !! If you have any idea of implementations using the provider (ideas that pop into my head right now: implementing Grover's algorithm, implementing LDPC codes, expanding the grover notebook to make it solve a more real life application (train timetable scheduling for example), maybe looking at Quantum Chemistry algorithms too?). If then you find some interesting notebook drafts, we would be so happy to include them in our examples. We are also always happy to hear feedback if you find any issue with the provider or examples, and are more than open if you find improvement or fixes.

Furthermore we are polishing the details to soon release a private beta in the upcoming weeks, that will use the provider here to interact with a real quantum chip. If you are interested to join, please let us know :smile: 

And finally, Alice & Bob is hiring on a lot of positions at the moment. My team, maintaining this project, is looking for a DevOps (https://jobs.lever.co/alice-bob/87562107-21b5-407f-9cac-3d2e4dbde095) and a Team Lead (https://jobs.lever.co/alice-bob/1a0b7bd4-d65d-4c26-bb88-fb28c547909d) based in Paris, France. If you are interested, you are very invited to apply or reach out to me on LinkedIn for more information (Maxence Drutel).

Cheers :cat:

**Comment by oradomskyi** [comment]
Hello Maxence,

Exciting! I will take a look into implementing one of the algorithms you mentioned!😃

Cheers 😸
