### ISSUE TITLE
Migrate to Qiskit 1.0

### ISSUE THREAD

**Issue by frankharkins** [Alice-Bob-SW/qiskit-alice-bob-provider#38]
I'm making this issue because this project is part of the [Qiskit ecosystem](https://qiskit.github.io/ecosystem/).

We're introducing a requirement that all projects are compatible with Qiskit 1.0. New users will be using Qiskit 1.0 and we want to make sure any projects we guide them to work straight away.

See our [migration guide](https://docs.quantum.ibm.com/api/migration-guides) and let me know if you need any support (such as answering questions about Qiskit or code review). With Qiskit's new stability policy, this should be the last change needed for a while. We do value your project so let me know if you need any help migrating or have any other concerns.

**Comment by lprost** [comment]
Hi Frank,

Thank you so much for opening the issue, this is something we'll want to do eventually indeed.

However, I have a hard time figuring out how far we are from being compatible with Qiskit 1.0. I remember we struggled switching to 0.45 and eventually gave up, so we didn't rush to support Qiskit 1.0, especially given that we still haven't had issues or user complaints with 0.44.3 specifically.

Is there an easy way to identify the changes we'll have to make, or will we just have to go through all the documentation and check every point individually?

Cheers,

Laurent

**Comment by frankharkins** [comment]
@lprost we have a tool to detect deprecated imports, see https://docs.quantum.ibm.com/api/migration-guides/qiskit-1.0-features#qiskit-10-migration-tool. For everything else, I recommend using your test suite to identify broken code and referring to the migration guide for instructions on fixing it.

**Comment by MaxleDrut** [comment]
Hello @frankharkins , thank you again for the tips on the Qiskit 1.0 migration. We are almost done and I am currently testing our changes against example codes. However, during our migration we bumped a version of qiskit-aer and now experience very strong slownesses on emulations. We can no longer emulate circuits above 200 gates.

I have created a message on the Qiskit #aer Slack channel with more details about our issue. Would you please have some insights on this problem, or would you know some people you can raise the issue to?
https://qiskit.slack.com/archives/C88B13092/p1722262132133249

Max

**Comment by gschurck** [comment]
Hi @frankharkins, we did the migration to Qiskit 1.2 in the last release of our provider so we can close this.
