### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by migueltorrescosta** [Alice-Bob-SW/qiskit-alice-bob-provider#40]
Hey :wave: I believe there aren't many contributions yet, but for both internal and external contributors it would be useful to have a `CONTRIBUTING.md` file explaining how to setup the local testing environment. This ideally includes a installing python section ( [example](https://github.com/Qiskit/qiskit/blob/main/CONTRIBUTING.md#set-up-a-python-venv) ) and how to run tests locally ( [example](https://github.com/Qiskit/qiskit/blob/main/CONTRIBUTING.md#testing) ).

I mention this as running `pip install -e .` locally failed, probably due to a missing setup step. The same happens if I run `make install`, using the provided `Makefile`

```bash
❯ pip install -e .
<removed>
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      error: Multiple top-level packages discovered in a flat-layout: ['cmake', 'symengine'].
      
      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.
      
      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:
      
      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names
      
      To find more information, look for "package discovery" on setuptools docs.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by MaxleDrut** [comment]
Hello, as of my comment from the PR for Python 3.12, this issue is not due to a lack of setup, but the fact that the `symengine` module that Qiskit 0.44 depends on, is not compatible with Python 3.12

Using Python >= 3.8, <3.12 will solve this issue.

Still, I'll see how I can improve the documentation for open source contributors, thank you :)
