### ISSUE TITLE
BackendV2 error using qiskit 0.44

### ISSUE THREAD

**Issue by gzquse** [Alice-Bob-SW/qiskit-alice-bob-provider#47]
## Packages we installed 
```
pip install qiskit==0.44.3
pip install qiskit-alice-bob-provider
```

## Error 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[13], line 1
----> 1 from qiskit_alice_bob_provider import AliceBobLocalProvider
      2 from qiskit import QuantumCircuit, execute, transpile
      4 provider = AliceBobLocalProvider()

File /opt/conda/lib/python3.11/site-packages/qiskit_alice_bob_provider/__init__.py:19
      1 ##############################################################################
      2 # Copyright 2023 Alice & Bob
      3 #
   (...)
     16 
     17 # flake8: noqa: F401
---> 19 from .local import AliceBobLocalProvider
     20 from .remote import AliceBobRemoteProvider

File /opt/conda/lib/python3.11/site-packages/qiskit_alice_bob_provider/local/__init__.py:19
      1 ##############################################################################
      2 # Copyright 2023 Alice & Bob
      3 #
   (...)
     16 
     17 # flake8: noqa: F401
---> 19 from .provider import AliceBobLocalProvider

File /opt/conda/lib/python3.11/site-packages/qiskit_alice_bob_provider/local/provider.py:22
     19 from typing import Callable, Dict, List, Optional, Tuple
     21 import numpy as np
---> 22 from qiskit.providers import BackendV2, ProviderV1
     24 from ..processor.interpolated_cat import InterpolatedCatProcessor
     25 from ..processor.logical_cat import LogicalCatProcessor

ImportError: cannot import name 'BackendV2' from 'qiskit.providers' (unknown location)

## Expectation
Could you please provide us an runnable example for us to test the "cat qubit"

**Comment by gzquse** [comment]
Problem solved

**Comment by challenge2-team1** [comment]
the current stable version
![image](https://github.com/user-attachments/assets/5a379abc-eb74-4b09-9f1f-9dcad779328c)
